version: '3.1'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./mongodb/volume:/data/db
      - ./mongodb/mongod.conf:/etc/mongod.conf
      - ./mongodb/log/:/var/log/mongodb/
    env_file:
      - .env
    command: ['-f', '/etc/mongod.conf']
  oauth20v2:
    restart: always
    container_name: oauth20v2
    build:
      context: piloto_sistema_oauth20
      dockerfile: Dockerfile
    ports:
      - 9004:9004
    links:
      - mongodb
    depends_on:
      - mongodb
    env_file:
      - .env
  backend:
    restart: always
    container_name: backend
    build:
      context: piloto_sistema_backend
      dockerfile: Dockerfile
    ports:
      - 3004:3004
    env_file:
      - .env
  frontend:
    restart: always
    container_name: frontend
    build:
      context: piloto_sistema_frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
